"""What did not work, generated from the specification log and git.

    build_what_did_not_work(spec_path, commits) -> str
    git_log(root) -> list[Commit]

Every row in ``reports/specifications.csv`` is a trial. A trial is
*superseded* when a later row ran the same specification key (factor,
signal, weighting, holding months, deciles, sector flag) — the earlier
row is what the pipeline looked like before something changed. A trial
is *abandoned* when its factor never appears among the reported factors
or the French replications — the diagnostics. Each gets one line:
when, what, its net Sharpe, and the first commit after it, which is the
commit that superseded it. Facts only; the interpretation is in the
README's own "What did not work" section and stays hand-written
(BUILD_PLAN step 8.4, ruling 4).

The current row of every key and every reported factor is not listed:
what works is in results.md.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import polars as pl

from backtester.run import REPORTED

KEEP = set(REPORTED) | {"hml_replica", "rmw_replica"}
MARKER = "<!-- below this line is written by the research_log agent -->"
KEY = ["factor", "signal", "weighting", "holding_months", "n_deciles", "no_sector"]


@dataclass(frozen=True)
class Commit:
    sha: str
    when: datetime
    subject: str


def git_log(root: Path) -> list[Commit]:
    """Every commit, oldest first, with its committer time."""
    out = subprocess.run(
        ["git", "log", "--reverse", "--format=%h%x1f%cI%x1f%s"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    commits = []
    for line in out.stdout.splitlines():
        sha, when, subject = line.split("\x1f")
        commits.append(Commit(sha, datetime.fromisoformat(when), subject))
    return commits


def superseding_commit(when: datetime, commits: list[Commit]) -> Commit | None:
    """The first commit after ``when``: the one that replaced this trial."""
    for c in commits:
        if c.when > when:
            return c
    return None


def classify(spec: pl.DataFrame) -> pl.DataFrame:
    """Every row with ``status`` in {current, superseded, abandoned}."""
    s = spec.with_columns(
        pl.col("timestamp").str.to_datetime(time_zone="UTC"),
        pl.col("note").fill_null("").str.contains("no-sector").alias("no_sector"),
        pl.int_range(pl.len()).alias("_row"),
    )
    last = s.group_by(KEY).agg(pl.col("_row").max().alias("_last"))
    s = s.join(last, on=KEY, how="left")
    return s.with_columns(
        pl.when(~pl.col("factor").is_in(list(KEEP)))
        .then(pl.lit("abandoned"))
        .when(pl.col("_row") < pl.col("_last"))
        .then(pl.lit("superseded"))
        .otherwise(pl.lit("current"))
        .alias("status")
    ).drop("_row", "_last")


def build_what_did_not_work(spec_path: Path, commits: list[Commit]) -> str:
    spec = pl.read_csv(spec_path, infer_schema_length=0)
    rows = classify(spec).filter(pl.col("status") != "current").sort("timestamp")
    n_total, n_listed = spec.height, rows.height
    lines = [
        "# What did not work — from the specification log",
        "",
        f"Generated by `backtester research-log` from {n_total} logged "
        f"specifications; {n_listed} were superseded or abandoned. One line "
        "each: when it ran, the note it was logged with, its net Sharpe, and "
        "the first commit after it. No interpretation here; that is the "
        "README's section of the same name.",
        "",
    ]
    for status in ("superseded", "abandoned"):
        sub = rows.filter(pl.col("status") == status)
        if sub.is_empty():
            continue
        title = (
            "Superseded: the same specification was run again later"
            if status == "superseded"
            else "Abandoned: diagnostics that never became a reported factor"
        )
        lines += [f"## {title}", ""]
        for r in sub.iter_rows(named=True):
            c = superseding_commit(r["timestamp"], commits)
            after = f'→ {c.sha} "{c.subject}"' if c else "→ no commit after it yet"
            sharpe = r["sharpe_net"] or "n/a"
            lines.append(
                f"- {r['timestamp']:%Y-%m-%d %H:%M} `{r['factor']}` "
                f"({r['signal']}, {r['weighting']}, hold {r['holding_months']}"
                f"{', no-sector' if r['no_sector'] else ''}) "
                f'net Sharpe {sharpe} — "{r["note"]}" {after}'
            )
        lines.append("")
    return "\n".join(lines)


def build(root: Path, spec_path: Path | None = None) -> Path:
    """Write reports/what_did_not_work.md and return its path.

    Everything above MARKER is regenerated; everything below it is the
    research_log agent's and is kept as it was.
    """
    spec_path = spec_path or root / "reports" / "specifications.csv"
    text = build_what_did_not_work(spec_path, git_log(root))
    out = root / "reports" / "what_did_not_work.md"
    tail = ""
    if out.exists():
        old = out.read_text(encoding="utf-8")
        if MARKER in old:
            tail = old.split(MARKER, 1)[1]
    out.write_text(text + "\n" + MARKER + tail, encoding="utf-8", newline="\n")
    return out


def git_log_with_bodies(root: Path, n: int = 200) -> str:
    """The last ``n`` commits with their bodies: what the agent reads to
    say what changed between a superseded run and the current one."""
    out = subprocess.run(
        ["git", "log", f"-{n}", "--format=%h %cI%n%s%n%n%b%n----"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    return out.stdout
